### ISSUE TITLE
ImportError: Unable to resolve ann backend: 'qdrant_txtai.ann.qdrant.Qdrant'

### ISSUE THREAD

**Issue by ScottM-wizard** [qdrant/qdrant-txtai#1]
Attempting your sample after the pip install that you show, I get this:

ImportError: Unable to resolve ann backend: 'qdrant_txtai.ann.qdrant.Qdrant'

pip3 install qdrant-txtai does not seem to cover everything.

**Comment by kacperlukawski** [comment]
Hi @ScottM-wizard! Are you sure your txtai application is running in the same pip environment as the one you install the package in? How do you launch your application? Programatically or via YAML?
